Repository GSG-FC02/Library-project, pull requests merged in 2021-04, with the labels that each got.

#2 add file structer
  JS/index.js
  JS/qoute.js
  JS/search.js
  css/style.css
  html/library.html
  html/qoute.html
  html/search.html
  images/img_library/pic1.jpg
  images/img_library/pic10.jpg
  images/img_library/pic11.jpg
  images/img_library/pic12.jpg
  images/img_library/pic13.jpg
  images/img_library/pic14.jpg
  images/img_library/pic15.jpg
  images/img_library/pic16.jpg
  images/img_library/pic17.jpg
  images/img_library/pic18.jpg
  images/img_library/pic19.jpg
  images/img_library/pic2.jpg
  images/img_library/pic20.jpg
  images/img_library/pic3.jpg
  images/img_library/pic4.jpg
  images/img_library/pic5.jpg
  images/img_library/pic6.jpg
  images/img_library/pic7.jpg
  images/img_library/pic8.jpg
  images/img_library/pic9.jpg
  images/index.png
  images/search 1.png
  index.html
Labels: awaiting-review

#3 edite file structere
  common/common.html
  common/common.js
  common/style.css
  index/main.js
  index/style.css
  library/index.html
  library/main.js
  library/style.css
  qoute/index.html
  qoute/main.js
  qoute/style.css
  search/index.html
  search/main.js
  search/style.css
Labels: Done

#10 README file
  README.md
Labels: Done

#18 Home JS
  index/main.js
Labels: Done

#22 Home folder
  home/main.js
  index/main.js
  index/style.css
Labels: awaiting-review

#21 search page
  Relates
  search/index.html
  search/style.css
Labels: Done

#19 quote page
  qoute/index.html
  qoute/main.js
  qoute/style.css
Labels: Done

#24 quote js
  images/img_library/pic1.jpg
  images/img_library/pic10.jpg
  images/img_library/pic11.jpg
  images/img_library/pic12.jpg
  images/img_library/pic13.jpg
  images/img_library/pic14.jpg
  images/img_library/pic15.jpg
  images/img_library/pic16.jpg
  images/img_library/pic17.jpg
  images/img_library/pic18.jpg
  images/img_library/pic19.jpg
  images/img_library/pic2.jpg
  images/img_library/pic20.jpg
  images/img_library/pic3.jpg
  images/img_library/pic4.jpg
  images/img_library/pic5.jpg
  images/img_library/pic6.jpg
  images/img_library/pic7.jpg
  images/img_library/pic8.jpg
  images/img_library/pic9.jpg
  qoute/index.html
  qoute/main.js
  qoute/style.css
Labels: Done

#20 Library pae
  library/index.html
  library/main.js
  library/style.css
Labels: in-progress

#26 more descriptive name Tag
  library/index.html
  library/main.js
  library/style.css
Labels: awaiting-review

#14 common elements
  common/common.html
  common/common.js
  common/style.css
Labels: awaiting-review

#27 Creat Search JS page
  search/index.html
  search/main.js
  search/style.css
Labels: Done
